Add note section for third party rapprovers
BCStudentSoftwareDevTeam/lsf pull request #367
Opened 2022-09-05 18:19 UTC by sreynit02

This PR fixes issue #358 : "The financial aid and saas reviewers should be able to manage notes on their approval pages. Currently there is a disabled input box that shows only labor notes. We should change it so that they have a way to view and add notes without having to approve and deny the form. Same interface pretty much as the current View Notes action on the overloads page."

Did: Added a textarea and a Save Note button on `/admin/saasOverloadApproval/formId`. 
Added a function called `overloadNoteInsert` in `financialAidOverload.js `file to handle note insertion from the financialOverload page.

Test: 
- Submit an Overload form for a student. An Overload Form is created when the total labor hour for student is over 20. 
- Log in as Financial Aid and navigate `http://0.0.0.0:8080/admin/financialAidOverloadApproval/<formId>`. Under "Financial Aid Note", add a note and click "Save Note". The page should reload and clear the text. Check the note table in php or mysql workbench, a note entry should be created for the note you just input.
-  Log in as Saaa admin and navigate `http://0.0.0.0:8080/admin/saasOverloadApproval/<formId>`. Under "Saas Note", add a note and click "Save Note". The page should reload and clear the text. Check the note table in php or mysql workbench, a note entry should be created for the note you just input.

2022-09-14 14:15 UTC, tylerpar99 requested changes

2022-09-14 14:15 UTC, tylerpar99 commented on app/static/js/financialAidOverload.js
> +function overloadNoteInsert(textareaID, buttonID) {
A good variable name, ideally verbs come first. I would recommend the variable be switched to insertOverloadNote.

2022-09-14 14:15 UTC, tylerpar99 commented on app/static/js/financialAidOverload.js
> +  var overloadNotes = $("#" + textareaID).val();
Is this a single note? or a list of notes? I would change it to overloadNote if it is a single note being grabbed. However, if it is multiple you can ignore this comment.

2022-09-16 13:38 UTC, bledsoef approved these changes, later dismissed

2022-09-16 19:03 UTC, tylerpar99 approved these changes

2022-09-16 19:14 UTC, BrianRamsay requested changes
The financial aid notes should be added as financial aid notes, not 'Labor' notes. It looks like this is broken for the notes added from the "View Notes" action on the overload forms list as well (broken before you).

Also, there is no way to view the notes on the approval screen itself, which was part of the ticket. It can be the same UI as the View Notes action has, which will make it simpler, and you can replace the Labor Notes text area.

2022-10-04 20:12 UTC, sreynit02 commented
@BrianRamsay did you mean this "View Note" on this modal?

![image](https://user-images.githubusercontent.com/59736834/193916669-de36da82-4e0d-48e4-a7dc-fac9c15c0d5f.png)

2022-10-31 19:45 UTC, Andersonstettner reviewed
Add Label to notes box for SAAS

2022-11-09 21:01 UTC, sreynit02 commented
> 

fixed

2022-11-10 15:09 UTC, Andersonstettner requested changes
Currently, the only way to see notes that have been left is to back out of the overload approval form and view the notes modal but we also need to see all of the notes that have been left while looking at the overload approval form. It would also need to be updated if a user leaves a new note on the page.

2022-11-11 18:49 UTC, Andersonstettner requested changes
If the user adds a long note, after a certain point, the note will not actually be submitted. The page will be reloaded and the note will disappear from the input box but it will not show up in the Notes log or in the database.

2022-11-11 19:35 UTC, Karina-Agliullova commented
![image](https://user-images.githubusercontent.com/68787691/201416690-26973354-a3b5-4bb5-a90a-31e8b4b83dc0.png)
Looks great! Remove the labels for other note modals. Having the title for notes is enough. If we include the label, it is kind of redundant

2022-11-14 22:35 UTC, gahimbaref commented
There is no limit to how much you can expand the text box
![image](https://user-images.githubusercontent.com/89202583/201782227-a3c4bf07-d69c-4da7-a817-ef628b1800be.png)

2022-11-15 14:58 UTC, Andersonstettner commented
> There is no limit to how much you can expand the text box ![image](https://user-images.githubusercontent.com/89202583/201782227-a3c4bf07-d69c-4da7-a817-ef628b1800be.png)

I would say this is not actually an issue. Being able to expand the box is an accessibility thing so we would want to allow it to get as big as the user wants, regardless of the size of the modal.

2022-11-16 21:50 UTC, sreynit02 commented
> If the user adds a long note, after a certain point, the note will not actually be submitted. The page will be reloaded and the note will disappear from the input box but it will not show up in the Notes log or in the database.

Fixed!

2022-11-16 22:27 UTC, gahimbaref commented
It seems as though the number of notes is not being incremented correctly. For example, there might be 4 notes, but it will show up as "View Notes(2)". 

Also, if you make heggens a saasAdmin but not a labor admin and not a financial aid admin, when you add a note, the number stays the same.

![image](https://user-images.githubusercontent.com/89202583/202306255-1a995913-337f-48ea-91d7-193d11a43bba.png)

2022-11-18 18:42 UTC, Andersonstettner requested changes
It's looking good. Two things, you didn't remove the second notes label in the view modal and, the sorting of the notes is different, they should be sorted the same way wherever they are.

2022-11-18 20:42 UTC, sreynit02 commented
> It's looking good. Two things, you didn't remove the second notes label in the view modal and, the sorting of the notes is different, they should be sorted the same way wherever they are.

fixed!

2022-11-18 21:58 UTC, gahimbaref approved these changes
looks good!

2022-11-21 15:23 UTC, BrianRamsay approved these changes
Looks good! Thanks.

2022-11-21 15:24 UTC, merged