Allow Supervisors Limited Student and Form Search Capabilities
BCStudentSoftwareDevTeam/lsf pull request #383
Opened 2022-09-19 14:15 UTC by bledsoef

Issue #366 sub-issue of #359 Epic.

## Changes
- Allowed supervisors access to the form search and student search pages and moved those out of the administrator's dropdown menu.
- Created a new logic file which houses student search logic and created the function, limitSearch, which takes in a list of users that were going to be displayed for the student search, and filtered out all students that the current user does not have access to.
- Tested limitSearch in new test file test_search.
- Adjusted queries and conditionals in the main/formSearch.py controller which made it so a user can only search for forms in their department and with other supervisors or students in those departments.

## How to Test
- As an admin, click on the form search and student search pages and confirm that the administrators can see all students, departments and supervisors.
- Then switch to a supervisor with one to a few departments (bolsters is a good one as she just is attached to math) and confirm that their search results are limited only to the scope of their department.
- Run tests.

2022-09-23 13:53 UTC, BrianRamsay requested changes

2022-09-23 13:53 UTC, BrianRamsay commented on app/controllers/main_routes/formSearch.py
> +from app.controllers.main_routes import *
let's import only the symbols we need

2022-09-23 13:53 UTC, BrianRamsay commented on app/controllers/main_routes/formSearch.py
> +        departments = (Department.select(Department.DEPT_NAME)
we should probably select the whole Department record so that our results match up with the query on line 38

2022-09-23 13:53 UTC, BrianRamsay commented on app/controllers/main_routes/formSearch.py
> +                    .distinct())
These queries should be ordered the same way that the existing ones are (IMO)

2022-09-23 13:53 UTC, BrianRamsay commented on app/controllers/main_routes/search.py
> +from app.controllers.main_routes import *
same as above. import the symbols you need

2022-09-23 13:53 UTC, BrianRamsay commented on app/controllers/main_routes/search.py
> +        print("ADMINS")
remove debug output

2022-09-23 13:53 UTC, BrianRamsay commented on app/logic/search.py
> +                    )
This query is essentially the same as the new one in form search. Let's bring it out into its own function so we can a) test it and b) re-use it.

2022-09-23 13:53 UTC, BrianRamsay commented on app/logic/search.py
> +            newstudents.append(student)
let's make this iteration either a comprehension or use a function like `filter()`. More pythonic, and matches line 23

2022-09-23 13:53 UTC, BrianRamsay commented on app/templates/main/formSearch.html
> +                        </option>
instead of repeating the whole `<option>` element, just have the `if` around "selected"

2022-09-28 14:51 UTC, Andersonstettner requested changes
The admin view dropdowns looked fine but if I hit search when all of the drop downs were in their initial state I was thrown this ajax error: 
![image](https://user-images.githubusercontent.com/26262045/192810001-197dad34-3cf6-4c3c-9c70-706db1f435c2.png) 

Then, when I changed to a supervisor (I used your recommendation of bolsters) there was nothing in any of the dropdowns and when I clicked search I got thrown the same ajax error.

2022-09-30 18:30 UTC, Andersonstettner requested changes
Department dropdown is not adding in the data correctly.

2022-10-05 14:18 UTC, Andersonstettner approved these changes

2022-10-07 14:12 UTC, BrianRamsay requested changes

2022-10-07 14:12 UTC, BrianRamsay commented on app/controllers/main_routes/formSearch.py
> +        departments = [department for department in departments]
If you're just turning it into a list use `list()`

2022-10-07 14:12 UTC, BrianRamsay commented on app/controllers/main_routes/formSearch.py
> +        departments = [department for department in departments]
This line isn't doing anything and the comment is wrong.

2022-10-07 14:12 UTC, BrianRamsay commented on app/controllers/main_routes/search.py
> +    # '[Bb]\d+' == is the search a bnumber
This comment isn't very readable. I would just use english to explain it rather than repeat the confusing code

2022-10-07 14:12 UTC, BrianRamsay commented on app/static/js/formSearch.js
> +  console.log(departmentID)
Debug output

2022-10-07 14:12 UTC, BrianRamsay commented on app/logic/search.py
> +def limitSearch(students, currentUser):
This should have a clearer name, like `limitSearchByUserDepartment` or something

2022-10-26 17:29 UTC, BrianRamsay approved these changes

2022-10-26 17:37 UTC, BrianRamsay approved these changes

2022-10-26 17:37 UTC, merged