Rework supervisor portal 362
BCStudentSoftwareDevTeam/lsf pull request #386
Opened 2022-10-12 12:57 UTC by bledsoef

2022-10-25 19:51 UTC, sreynit02 commented
When the accordion is clicked on, the corner of the accordion looks like this:

2022-10-28 17:56 UTC, Andersonstettner requested changes
The new page is looking good. A few things:
1. Make sure the accordion stays open when the user searches with none of the fields filled in and the "At least one field..." error message is thrown.

2. In the "Department" dropdown the second option is a blank space but if you select it, it says "Department". If it is not supposed to be there remove it and if it is supposed to be there make sure "Department" shows up in the drop down.
Figures:  
![image](https://user-images.githubusercontent.com/26262045/198701108-b8b1c162-33fe-4cf5-9120-cde28c9d3f20.png)
![image](https://user-images.githubusercontent.com/26262045/198701172-a840459c-fe61-43c5-99c3-184453294d13.png)

3. Add an indication that the Form Table is separate from the "Form Search" accordion. 

4. Is the arrow on the right of the accordion body supposed to indicate open state of the accordion? If so then it is broken, if not then it might be nice to remove it since it could be confusing to users.

5. What is the purpose of the green indicator to the left of "Labor Status Form" in a students LSF modal? In my opinion the does not look very good due to how pixelated it is and there does not seem to be a purpose for it since there is no differentiation when a LSF is submitted, accepted, or rejected. 
Figure:
![image](https://user-images.githubusercontent.com/26262045/198702151-32d99b46-8a11-4bab-bbb9-11ee4110a963.png)

6. There are two broken smoke tests: 
![image](https://user-images.githubusercontent.com/26262045/198706555-015e9d0c-be62-44e2-b481-4acb624175b3.png)

2022-10-28 19:55 UTC, Andersonstettner requested changes

2022-10-28 19:55 UTC, Andersonstettner commented on app/logic/search.py
> +    newstudents = []
camelCase?

2022-10-28 19:55 UTC, Andersonstettner commented on app/logic/search.py
> +    return departments
Make the return of this function and the previous function (studentDbToDict) consistent. They should both either be variables or just return the query for this function.

2022-11-02 14:03 UTC, tylerpar99 commented
> The new page is looking good. A few things:
> 
> 1. Make sure the accordion stays open when the user searches with none of the fields filled in and the "At least one field..." error message is thrown.
> 2. In the "Department" dropdown the second option is a blank space but if you select it, it says "Department". If it is not supposed to be there remove it and if it is supposed to be there make sure "Department" shows up in the drop down.
>    Figures:
>    ![image](https://user-images.githubusercontent.com/26262045/198701108-b8b1c162-33fe-4cf5-9120-cde28c9d3f20.png)
>    ![image](https://user-images.githubusercontent.com/26262045/198701172-a840459c-fe61-43c5-99c3-184453294d13.png)
> 3. Add an indication that the Form Table is separate from the "Form Search" accordion.
> 4. Is the arrow on the right of the accordion body supposed to indicate open state of the accordion? If so then it is broken, if not then it might be nice to remove it since it could be confusing to users.
> 5. What is the purpose of the green indicator to the left of "Labor Status Form" in a students LSF modal? In my opinion the does not look very good due to how pixelated it is and there does not seem to be a purpose for it since there is no differentiation when a LSF is submitted, accepted, or rejected.
>    Figure:
>    ![image](https://user-images.githubusercontent.com/26262045/198702151-32d99b46-8a11-4bab-bbb9-11ee4110a963.png)

1. Done.
2. DB issue is not a code issue, there is a department record in the backup DB that has an empty name.
3. Done.
4. Done.
5. Done.

2022-11-02 14:10 UTC, tylerpar99 commented
> When the accordion is clicked on, the corner of the accordion looks a bit crooked: ![image](https://user-images.githubusercontent.com/59736834/197868795-2842dc29-55e2-4c46-b3df-18d66d4f075f.png)

fixed.

2022-11-03 13:34 UTC, Andersonstettner requested changes
It looks good, one minor thing I noticed is that, if a user does not select a field and they get the "At least one field must be selected." flash message, the flash message never goes away unless the user closes it themselves. 

Also, a more nitpick is I don't really like how the accordion behaves in that case, searching with no fields selected. I think it might be good to disable the search button until one of the fields has been selected or have a different action happen when that case occurs.

2022-11-09 14:05 UTC, tylerpar99 commented
> It looks good, one minor thing I noticed is that, if a user does not select a field and they get the "At least one field must be selected." flash message, the flash message never goes away unless the user closes it themselves.
> 
> Also, a nitpick I have is I don't really like how the accordion behaves in that case, searching with no fields selected. I think it might be good to disable the search button until one of the fields has been selected or have a different action happen when that case occurs.

Fixed.

2022-11-10 21:02 UTC, martinj2-dot approved these changes
Looks good!

2022-11-10 21:03 UTC, Karina-Agliullova approved these changes
Good work!

2022-11-11 18:54 UTC, Andersonstettner commented on app/logic/search.py
> +    dbtodict =  {'username': usernameFromEmail(student.STU_EMAIL.strip()),
camelCase?

2022-11-14 13:16 UTC, tylerpar99 commented on app/logic/search.py
> +    dbtodict =  {'username': usernameFromEmail(student.STU_EMAIL.strip()),
Fixed.

2022-11-14 14:23 UTC, AndersonStettner approved these changes

2022-11-21 14:54 UTC, BrianRamsay approved these changes

2022-11-21 14:54 UTC, merged