All labor admins and supervisors should be able to evaluate any student in there department.
BCStudentSoftwareDevTeam/lsf pull request #387
Opened 2022-10-17 13:27 UTC by tylerpar99

This PR fixes #363 

<h3>Summary: </h3><p>This PR will allow all Labor admins and supervisors to evaluate any student in their department. The logic works when a supervisor or Labor Admin is assigned to multiple departments. </p>

<h3>To Test:</h3> <p>You will by default be "heggens" and he by default is a labor admin. While logged in as him make sure you are using staging and prod data. Open up the term "AY 2021-2022" and make sure evaluations are open and the term is open. You should now be able to go to the Supervisor Portal and search with terms "AY 2021-2022" and Department "Computer Science" and click "Labor History" on the Supervisor Portal table and the evaluate button should be visible. Now take away admin privileges and you should be able to click on any labor history in your department that you are not a direct supervisor for and the evaluate button should also be visible.</p>

<h3>Note:</h3><p>This branch is branched off of PR #386 which is branched off of PR #383.</p>

2022-10-26 18:51 UTC, sreynit02 reviewed
- Links: I think the brower's back button,  "Save for later" and "Submit Final Evaluation" button should lead the user back to the result table of the search. If a supervisor has multiple students to evaluate they will have to search so many times to complete all the evaluations.

2022-10-26 19:24 UTC, sreynit02 requested changes
Overall functionality works great. See the comments above for changing links suggestion.

2022-11-16 19:51 UTC, Andersonstettner commented on app/static/js/supervisorPortal.js
> +function runformSearchQuery(newData='', cookie) {
capitalize f?

2022-12-05 15:56 UTC, BrianRamsay approved these changes

2022-12-05 16:08 UTC, BrianRamsay requested changes
When you run into the error `app.logic.userInsertFunctions.InvalidUserException: B00291242 not found in Tracy database` it completely hoses the form search. We need to handle that more gracefully, so that the record is either marked or dropped, rather than the whole table throwing a javascript error at the user. My search was for Spring 2022. The fourth page throws an error.

2022-12-07 14:28 UTC, tylerpar99 commented
> When you run into the error `app.logic.userInsertFunctions.InvalidUserException: B00291242 not found in Tracy database` it completely hoses the form search. We need to handle that more gracefully, so that the record is either marked or dropped, rather than the whole table throwing a javascript error at the user. My search was for Spring 2022. The fourth page throws an error.

Talked it over and we agreed it is an development specific issue.

2022-12-07 20:49 UTC, BrianRamsay approved these changes

2022-12-07 20:50 UTC, merged