Supervisor search presets
BCStudentSoftwareDevTeam/lsf pull request #395
Opened 2022-12-14 16:30 UTC by tylerpar99

Summary:
Created buttons for potential preset options on the supervisor portal. When a preset option is clicked we create a dictionary based on the presets filtering. With these changes, there are also two new options in the `getDatatableData()` function it will now allow requests for the current user and current term filtering as well as limit non-admins to only information within their department. We have also patched a bug that would attempt to check Tracy first before checking our DB we now have it check our DB first then Tracy and if that fails we pass on the record.

To Test: 
Try each preset and ensure the result match as expected. Also if you click pending forms or current term and click through each page you should see that no result throws an error.

2022-12-14 16:32 UTC, tylerpar99 commented
To Do: 

- Confirm that preset options are valid
- Do we want to only show current user evaluations (current behavior) or whole departments?
- I'm Not sure how to test that the bug patch for checking Tracy first is valid or if that is even necessary.

2023-02-13 20:11 UTC, Andersonstettner requested changes

2023-02-13 20:11 UTC, Andersonstettner commented on app/templates/main/supervisorPortal.html
> +  <button class="btn btn-primary" type="button" id="superviseesPendingForms">Upcomings Students</button>
Change to "Pending Forms"

2023-02-13 20:45 UTC, Andersonstettner requested changes

2023-02-13 20:45 UTC, Andersonstettner commented on tests/code/test_formSearch.py
> +            print(runGetDatatableData)
Remove print statements

2023-07-18 15:55 UTC, AndersonStettner submitted a review, later dismissed

2023-07-18 15:55 UTC, AndersonStettner commented on app/controllers/main_routes/main_routes.py
> +    print("entered function")
Remove Print

2023-07-18 15:55 UTC, AndersonStettner commented on app/controllers/main_routes/main_routes.py
> +            print("true")
Remove

2023-07-18 15:55 UTC, AndersonStettner commented on app/controllers/main_routes/main_routes.py
> +            print("false")
Remove

2023-07-18 15:55 UTC, AndersonStettner commented on app/controllers/main_routes/main_routes.py
> +            print("printing somethintg")
Remove

2023-07-18 15:55 UTC, AndersonStettner commented on app/controllers/main_routes/main_routes.py
> +        print("error")
Remove print, should we be catching a specific exception?

2023-08-29 16:22 UTC, BrianRamsay approved these changes

2023-08-29 16:24 UTC, merged