Date submitted eval 396
BCStudentSoftwareDevTeam/lsf pull request #402
Opened 2023-01-26 21:23 UTC by tylerpar99

Summary: 
Added the submitted date to student evaluation forms after they have been submitted. The program will access today's date when the form is submitted and then when the submission is accessed by the user will turn that date time field into the U.S. date format. 

To test:
You will have to create an LSF and a Form history for a student in the development non-backup data. Make the form for the term 2021-2022 and make sure in term management in LSF you set the final evaluations to open. You should now see Evaluate as an option on the student record modal in LSF (Click on the student's name in the Supervisor portal). Evaluate them. Now go back and check the form again and you should see the date attached at the top.

2023-02-08 21:58 UTC, sreynit02 approved these changes
Looks good to me!

2023-02-09 16:03 UTC, BrianRamsay requested changes

2023-02-09 16:03 UTC, BrianRamsay commented on app/controllers/main_routes/studentLaborEvaluation.py
> +        correctFormat = listDate[1] + '-' + listDate[2] + '-' + listDate[0]
We should use `strftime("%m-%d-%Y")` for this

2023-02-10 21:46 UTC, sreynit02 approved these changes
Looks good!

2023-02-14 21:30 UTC, BrianRamsay approved these changes

2023-02-14 21:30 UTC, merged