Reset evals 397
BCStudentSoftwareDevTeam/lsf pull request #403
Opened 2023-02-01 20:57 UTC by solijonovam

What we did:

-Added a 'reset' button, and a modal that pops up once the 'reset' button is clicked
-The modal confirms resetting the form
-once confirmed, the form will be deleted
-redirects to the original form

To test:
-Evaluate a student
-Click 'show evaluation' 
-once in the form, 'reset' button will be there. 
-reset the form
-run the test suite

2023-02-03 21:29 UTC, tylerpar99 commented
This PR isn't ready yet still working on the testing suite.

2023-02-09 15:49 UTC, gahimbaref commented on app/controllers/main_routes/studentLaborEvaluation.py
> +    # print(sleForm.isSubmitted)
Forgot to remove debug print statements

2023-02-09 15:56 UTC, gahimbaref commented on app/controllers/main_routes/studentLaborEvaluation.py
> +        print("here?")
This one too

2023-02-09 19:52 UTC, tylerpar99 commented on app/controllers/main_routes/studentLaborEvaluation.py
> +    # print(sleForm.isSubmitted)
This PR is still being worked on

2023-02-09 20:20 UTC, sreynit02 requested changes
I suggest that the modal should have a bit more explanation of what will be erased once they successfully reset.

2023-02-09 21:15 UTC, sreynit02 requested changes
![image](https://user-images.githubusercontent.com/59736834/217940533-a271cd24-b55b-41fc-b5d9-1fd1f6644ee0.png)
The modal looks empty, I suggest adding a body to the modal say sth along this line. "This action will erase comments in all section."

2023-02-10 20:22 UTC, tylerpar99 commented
> ![image](https://user-images.githubusercontent.com/59736834/217940533-a271cd24-b55b-41fc-b5d9-1fd1f6644ee0.png) The modal looks empty, I suggest adding a body to the modal say sth along this line. "This action will erase comments in all section."

Fixed

2023-02-10 20:42 UTC, sreynit02 approved these changes
Great job!

2023-02-10 21:46 UTC, merged