Update departments account and org from Tracy.
BCStudentSoftwareDevTeam/lsf pull request #406
Opened 2023-02-21 21:47 UTC by tylerpar99

This fixed PR #378 

Summary: This PR changes the file `updateStudentRecords.py` to `updateDBRecords.py`. We then add to that file a count of failed and updated department codes. In `userInsertFunctions.py` we add a new function that will update all department account and org codes based on what Tracy has for that department name. We also added a new function to Tracy to get department data from a department name and return the account and org code. We also added to the test suite to include the new department updating function and updated a test that resulted from adding a new department to UTE.

To Test: Run the test suite. Reset from-backup and export flask environment to staging. Not in the terminal type "python updateDBRecords.py" and you will see that some fail and some pass. Fails are from departments that no longer exist. Success proves that the new function updates departments.

2023-03-03 16:39 UTC, Andersonstettner commented on app/logic/userInsertFunctions.py
> +    departmentsFromDB = Department.select()
Not a blocker and really nitpicky but I think it would be nice to keep naming the same on all of these so it would be departmentsInDB

2023-03-22 21:03 UTC, sreynit02 requested changes
Just one easy comment to resolve. After that you're all set!

2023-03-22 21:03 UTC, sreynit02 commented on app/logic/userInsertFunctions.py
> +    departmentsFromDB = Department.select()
agreed!

2023-08-30 18:21 UTC, stevensonmichel commented on app/logic/tracy.py
> +        """
You might consider correcting the name of the function. getDepartmentsFromName implies that you are getting multiple departments, which is not true.

2025-08-18 20:39 UTC, BrianRamsay commented
Implemented elsewhere in the last 2 years

2025-08-18 20:39 UTC, closed without merging