Error student overload 373
BCStudentSoftwareDevTeam/lsf pull request #409
Opened 2023-03-20 20:52 UTC by solijonovam

this PR resolves issue #373 

Summary: Redirect students back to labor history page rather than access denied page

To Test:
-fill out an lsf form for an overload 
- switch user to student
- /studentOverloadApp/<formHistoryId>
- fill out form and submit

2023-03-24 19:50 UTC, sreynit02 requested changes, later dismissed
Looks good, just need to delete print statements and fix merge conflict.

2023-03-24 19:50 UTC, sreynit02 commented on app/controllers/main_routes/laborHistory.py
> +                    print("len wrong?")
delete comment?

2023-03-24 19:50 UTC, sreynit02 commented on app/controllers/main_routes/laborHistory.py
> +            print("Not currentuser")                # Not logged in
delete comment?

2023-08-31 15:55 UTC, hoerstl approved these changes

2025-08-18 20:49 UTC, BrianRamsay approved these changes

2025-08-18 20:50 UTC, merged