Added email button to email labor student position information
BCStudentSoftwareDevTeam/lsf pull request #420
Opened 2023-08-25 15:13 UTC by andersoncedu

Issue:
Needed the ability to send an email from the position view page as a supervisor.

Fixes:
Added a mailto in JavaScript which gets student information and information about the labor position the student is enrolled in and opens an email to the labor department.

Test:
Go to supervisor portal, complete form search information to find a student. Click the student's name on the table which appears after the search. From there Click the Email Labor button which should open the default email handler on your system and populate the body and subject with the appropriate information from the modal. 

Fixes #418

2023-08-25 15:18 UTC, AndersonStettner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create an easy contact button. #418](https://trello.com/c/Y4FCOFf9/686-create-an-easy-contact-button-418)

2023-08-29 21:18 UTC, hoerstl requested changes

2023-08-29 21:18 UTC, hoerstl commented on app/templates/snips/studentHistoryModal.html
> +  <div class="btn btn-primary" id="easyEmail" onClick="mailPositionToLabor()"><span>Email Labor</span></div>
We have many concerns regarding the position of the button. The dual council has decided that it makes the header too large from what lsf had previously. Consider placing the button to the left of the Rehire button within the footer.

2023-08-29 21:18 UTC, hoerstl commented on app/templates/snips/studentHistoryModal.html
> +  <div class="btn btn-primary" id="easyEmail" onClick="mailPositionToLabor()"><span>Email Labor</span></div>
Also, consider changing the id of this element in both the CSS and this line to be "emailLabor" instead of easyEmail. Right now, the id doesn't reflect the recipient of the email.

2023-08-29 21:18 UTC, hoerstl commented on app/static/js/laborhistory.js
> +  body = body.replace(/\s+/g, ' ')
Whenever we click the button we only see the first three pieces of information being displayed.
![image](https://github.com/BCStudentSoftwareDevTeam/lsf/assets/89316750/0d0ba00f-470e-48d4-a5d7-0c97fdea6142)
Specifically, we saw this issue when looking at Isaac white's work at IS&S. It seems that since we have not encoded any of the special characters that might appear in the body, the ampersand (&) in IS&S breaks the mailto link and effectively truncates the body prematurely. You will need to encode the fully formed body before you open the mailto link so that special characters aren't interpreted as operators.

2023-08-29 21:18 UTC, hoerstl commented on app/static/js/laborhistory.js
> +  body = body.replace(/\s+/g, ' ')
The full department (ID) was "Information Systems & Services".

2023-08-29 21:18 UTC, hoerstl commented on app/templates/snips/studentHistoryModal.html
>  <div class="modal-body" id="modalid">
This id makes you all look like saints in comparison and our lord and Savior Brian is upset at this blasphemy. Please fix the great mistakes of your ancestors and change this id to please the gods.

2023-08-31 13:08 UTC, BrianRamsay requested changes

2023-08-31 13:08 UTC, BrianRamsay commented on app/templates/snips/studentHistoryModal.html
> +  <div class="btn btn-primary" id="easyEmail" onClick="mailPositionToLabor()"><span>Email Labor</span></div>
Also let's avoid using an onclick. We try not do do that anymore.

2023-08-31 13:12 UTC, BrianRamsay commented on app/static/js/laborhistory.js
> +  body = body.replace(/\s+/g, ' ')
Encoding the whole body might cause a problem with the newline encodings already added.

&amp; is the encoding for ampersands, so a quick and dirty option would be to replace & with &amp; in the department and maybe position text.

But you can experiment and see what works the best.

2023-09-22 18:13 UTC, doucoureb commented
looks good!

2023-10-05 12:35 UTC, AndersonStettner approved these changes

2023-10-05 12:37 UTC, merged