Added endpoint for CELTS to hit to get CELTS labor info
BCStudentSoftwareDevTeam/lsf pull request #421
Opened 2023-08-25 16:44 UTC by AndersonStettner

CELTS would like to have their labor students position title and time worked at CELTS displayed in CELTS-Link so I have created an endpoint to hit from CELTS-Link to get that information.

2023-09-21 15:05 UTC, AndersonStettner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Extend functionality of the Program Manager accordion #991](https://trello.com/c/TMKjPwUc/657-extend-functionality-of-the-program-manager-accordion-991)

2023-09-26 15:02 UTC, andersoncedu commented
![image](https://github.com/BCStudentSoftwareDevTeam/lsf/assets/97543993/f37a0721-c6d5-433f-bad7-0c334871ea09)
Getting a no module named "flask_restful" error.

2023-09-26 15:54 UTC, andersoncedu commented
I see no other issues, looks good.

2023-11-07 16:27 UTC, andersoncedu commented
Other than tests failing because development hasn't been merged recently looks good!

2023-11-15 17:07 UTC, hoerstl requested changes

2023-11-15 17:07 UTC, hoerstl commented on app/logic/apiEndpoint.py
> +    givenOrgCode = (Department.select(Department.departmentID)
Should probably be named orgDepartmentCodes or something to that effect since it holds department IDs.

2023-11-15 17:07 UTC, hoerstl commented on app/logic/apiEndpoint.py
> +    laborFormDict = {}
Consider using a defaultdict from the collections module in python:
`from collections import defaultdict`

2023-11-16 21:32 UTC, hoerstl requested changes
Looks splendid after these fixes

2023-11-16 21:32 UTC, hoerstl commented on app/controllers/api_routes/apiClasses.py
> +        if app.config['ENV'] == 'production' and not requestersIp == appConfig['VALID_REQUEST_IP']:
Consider using the conditional statement to minimize the usage of the not keyword:
`requestersIp != appConfig['VALID_REQUEST_IP']`

2023-11-16 21:32 UTC, hoerstl commented on app/logic/apiEndpoint.py
> +        orgCode = 2084
Consider setting this orgCode default as the default parameter in the function definition. Or, you might consider making this a config constant if we plan on changing this at all or not if this is temporary.

2023-11-16 21:42 UTC, hoerstl commented on app/logic/apiEndpoint.py
> +def getLaborInformation(orgCode = "", bNumber = ""):
Consider making the function definition look like this instead:
`def getLaborInformation(*, orgCode = "", bNumber = ""):`
Doing this makes it so we can't pass in these parameters using positional arguments and given that these pieces of information aren't particularly obvious, it's probably best we enforce use of keyword arguments here.

2023-11-17 16:04 UTC, hoerstl commented on app/logic/apiEndpoint.py
> +    orgDepartments = (Department.select(Department.departmentID)
You also need to change the variable name on line 36 to complete the variable usage

2023-11-17 16:59 UTC, hoerstl approved these changes
Looks good! It looked like tests passed.

2023-11-20 15:50 UTC, BrianRamsay approved these changes

2023-11-20 15:50 UTC, merged