441simple view
BCStudentSoftwareDevTeam/lsf pull request #459
Opened 2024-10-17 17:34 UTC by WackyWeaver

resolves: #441

2024-11-06 15:52 UTC, Karina-Agliullova approved these changes
Looks good!

2024-11-08 19:55 UTC, Mbeweg reviewed
Changes Requested

2024-11-08 19:55 UTC, Mbeweg commented on app/static/js/supervisorPortal.js
> +      fields = advancedColumnFieldMap[column]
Make this variable declaration and if statement a one-liner using a ternary operator
`let fields = buttonVal == "advanced"? advancedColumnFieldMap[column]:simpleColumnFieldMap[column];`

2024-11-08 19:55 UTC, Mbeweg commented on app/static/js/supervisorPortal.js
> +    // switches on button press it is technically the opposite of the current view
These comments are out of date. The value of the switchViewButton **is equal to** the current view in the most recent commit. Should probably remove or update.

2024-11-19 17:30 UTC, BrianRamsay requested changes
Just one small change

2024-11-19 17:30 UTC, BrianRamsay commented on app/static/js/supervisorPortal.js
> +    })
Let's pull out 240-248 into a resetColumnPicker function (or some other name), as it is basically identical to the code in the other branch (228-236). That will make each side of the conditional look a lot simpler, and we won't repeat the code.

2024-11-19 19:34 UTC, BrianRamsay approved these changes

2024-11-19 19:35 UTC, merged