Add permission for admin students for New Labor Status Form
BCStudentSoftwareDevTeam/lsf pull request #462
Opened 2024-11-05 17:06 UTC by stevensonmichel

## Issue: 
Previously, students who are also Labor Admins did not have access to the New Labor Status Form page. That was considered as a bug given that these students have the permissions to add submit labor status forms for students. 

## Solution: 
Through exploration, we discovered that in the backend such a logic to allow labor admin students to see the New Labor Status Form was already implemented. However, the sidebar was not displaying the New Labor Status Form for these students. So, we made changes there to reflect the privileges of accessibility for these students. 

## To test:
Assuming you're in the LSF directory
- source setup.sh
- database/reset_database.sh from-backup
- change the login username into a student who is a Labor Admin
- export FLASK_ENV=staging
- flask run
Now open the application and verify if New Labor Status Form is present as an option in the sidebar. 

Fixes Issue #1321
https://github.com/BCStudentSoftwareDevTeam/celts/issues/1321

2024-11-11 03:11 UTC, bledsoef requested changes
Functionality looks alright besides some tracy problems which are unrelated. Just might try to prevent duplicating code. Nice job!

2024-11-11 03:11 UTC, bledsoef commented on app/templates/sidebar.html
> +      {% elif currentUser.student and currentUser.isLaborAdmin %}
Could we potentially add this conditional to the other New Labor Status Form instead of duplicating all this code?

2024-11-11 20:45 UTC, hoerstl commented on app/templates/sidebar.html
> +      {% elif currentUser.student and currentUser.isLaborAdmin %}
Yessir. I've replaced the single if statement above with three so the sidebar components remain in order and removed the duplicate code.

2024-11-18 20:09 UTC, bledsoef approved these changes
LGTM

2024-11-18 20:09 UTC, merged